### ISSUE TITLE
fonts not inlined in css

### ISSUE THREAD

**Issue by lekkra** [remy/inliner#100]
If possible, fonts should be too inlined

**Comment by remy** [comment]
I appreciate this was a while ago, but can you create a sample case as per the contributing guide? Then we can create a fix based on it.

**Comment by HugoGresse** [comment]
fonts are inlined for me

**Comment by Lexicality** [comment]
It fails if you ask it to read a file and the fonts have querystrings:
```
lexr at optiplexr in ~/projects/inliner-test
$ node_modules/.bin/inliner fonts-querystring.src.html
warning: no such file: fonts-querystring.woff?
<head><style>@font-face{ src:url("data:application/octet-stream;base64,");}</style> </head>
```
https://gist.github.com/Lexicality/cce5d836473c57c407fd6af6b587e8d0

**Comment by Lexicality** [comment]
That said, I'm still having fonts not be inlined without a warning without query strings too, so I'll keep digging

**Comment by Lexicality** [comment]
Finally found the issue, the compiled CSS file had an absolute path in it, which didn't work when feeding the result into `inliner` as a string.

**Comment by remy** [comment]
I appreciate this was months ago, but do you want to take a shot at a PR? The tests are very easy to setup (follow the contributing doc - just need two HTML files). Thanks so much!
