### ISSUE TITLE
Option to ignore erros

### ISSUE THREAD

**Issue by marcelboettcher** [remy/inliner#104]
Hey. Thanks for the great work. 

I have a page where a url is escaped in a json structure, which is not resolved correctly with inliner.
For such cases I would prefer to have a option to ignore errors and just log them. I think it is a good idea to allow the developer to decide how to handle the error of an invalid uri - in this case. The resulting html can be good enough.

Example page:
http://finance.yahoo.com/news/united-gives-slightly-brighter-forecast-2q-revenue-114624054--finance.html

Would love to see this option beeing added.

Thanks!
Marcel

**Comment by remy** [comment]
Can you show me how it's being used, or are you simply calling the CLI on that URL?

**Comment by marcelboettcher** [comment]
CLI as well as my code produce the same result.

```
new Inliner(url, {encoding: 'utf-8'}, function(err, inlinedHtml) {
		if(err) {
			deferred.reject(err);
		} else {
			deferred.resolve(inlinedHtml);
		}
	});
```

**Comment by remy** [comment]
Oh, I see. It's bailing when it hits the duff URL:

```
❯ inliner http://finance.yahoo.com/news/united-gives-slightly-brighter-forecast-2q-revenue-114624054--finance.html
Invalid URI "http:////l.yimg.com//ts//api//res//1.2//a7RcmRbkGrGLwQ2v.eoRUQ--//YXBwaWQ9eWhvbWVydW47cT00MDtzbT0xO3c9NjAwO2g9MTI1NA--//https:////s.yimg.com//av//moneyball//ads//1465557018638-5668.jpg"
```

**Comment by remy** [comment]
I think this is actually a bug, any bad URLs shouldn't cause inliner to throw, it should be an opt-in to bail on bad urls.

**Comment by marcelboettcher** [comment]
even better, I agree!
