### ISSUE TITLE
inliner misses files when not using base path for URL

### ISSUE THREAD

**Issue by alexpmorris** [remy/inliner#107]
if I call something like

```
inliner http://example.com/test
```

and there is an element such as:

```
<script src="test.js"></script>
```

inliner will return a 404 on http://example.com/test.js instead of looking for http://example.com/test/test.js

then I tried the following, which seemed to make the 404 disappear.  HOWEVER, those files still appeared to be missing from the final combined HTML output:

```
<script src="./test.js"></script>
```

**Comment by remy** [comment]
The correct url to request *is* example.com/test.js though. Given the example you gave the relative path is `/` rather than `/test/`. 

Do you have a real world example of what you're seeing?

**Comment by alexpmorris** [comment]
This is basically what I was trying to roll up:

http://yourika.com/dbtest/

This app works fine in all the browsers that I tried.  None gave a 404 looking at `/` over `/dbtest/`.

**Comment by remy** [comment]
The latest release of inliner should keep the 404'ing URLs in the output, so if you run:

```
$ inliner http://yourika.com/dbtest/ > dbtest.html
```

You should see which are 404'ing. From my own test, it looks to be the loading image only. Can you check if you see anything different (and paste here)?

**Comment by alexpmorris** [comment]
I installed the latest version of inliner on npm, and this is the output I received:
```
>inliner http://yourika.com/dbtest/ >dbtest.html
? 404 on loading.gif
100%
Last job: 404 on loading.gif
```
However, this is the output I got in Chrome (Inspect/DevTools Console) when I tried loading dbtest.html:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///C:/myjunk/cc/gridstack.min.js 
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///C:/myjunk/cc/techan.min.js 
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///C:/myjunk/cc/pnotify.custom.min.js 
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///C:/myjunk/cc/jquery.webui-popover.min.js 
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///C:/myjunk/cc/w2ui-1.4.3.min.js 
```
So, it's still leaving those files out, while it seems to be including all the others.

**Comment by remy** [comment]
Are you certain these are being referenced in the html and not dynamically loaded via JavaScript?

**Comment by alexpmorris** [comment]
from `view-source:http://yourika.com/dbtest/`:

```
	<script src="techan.min.js"></script>
        <script src="gridstack.min.js"></script>
	<script src="pnotify.custom.min.js"></script>
	<script src="jquery.webui-popover.min.js"></script>
	<script src="w2ui-1.4.3.min.js"></script>
```
I don't believe so.  What I can say, which is especially strange is that inliner does seem to catch others that come right after those (no chrome error message).  One thing I did notice is that the ones that seem to have a problem have multiple `.` (ie. .min.js) in them, whereas the ones that seemed to load fine are all single `.` (ie.  xxxxx-xxx.js).

**Comment by remy** [comment]
Oh sod, they're all minified, inliner skips minified scripts by default. I caught that the other day when I actually wanted it inlined. That's a sort-of-bug/sort-of-feature. I'll see if I can make a PR to sort this.

**Comment by alexpmorris** [comment]
ah ok, glad we finally nicked that one!

**Comment by remy** [comment]
I appreciate this was months ago, but do you know if this works? I've merged a bunch of PRs and changes over the months, so I'm not 100% sure if this is fixed or not!

**Comment by alexpmorris** [comment]
yes, I believe the problem was solved, thank you!
