### ISSUE TITLE
images with srcset should be replaced with base64 as well or removed

### ISSUE THREAD

**Issue by marcelboettcher** [remy/inliner#108]
Hey,

just had an example where an image is defined with srcset in addition to src. So the normal behaviour should be to replace the srcset with base64 as well. I would suggest to add an option, which removes the srcset if src attribute exists to avoid unneccessary huge inlined files.

Example: http://www.airlinereporter.com/2016/07/happy-100th-birthday-boeing-heres-special-alaska-livery/

What do you think?

Cheers, Marcel

**Comment by remy** [comment]
Oh, ha, I just replied to your other issue, and yep - `srcset` needs supporting 👍

**Comment by remy** [comment]
I appreciate this was months ago, but do you want to take a shot at a PR? The tests are very easy to setup (follow the contributing doc - just need two HTML files). Thanks so much!
