### ISSUE TITLE
Not all js, css and fonts get inlined

### ISSUE THREAD

**Issue by marcelboettcher** [remy/inliner#109]
Hey,

a quick question. I use the options `{
        encoding: 'utf-8',
        inlinemin: true,
        skipAbsoluteUrls: false
    };
`
for http://www.airlinereporter.com/2016/07/happy-100th-birthday-boeing-heres-special-alaska-livery/

My result still contains a lot of external dependencies (js, css, fonts), as you can see here: 
http://lht-static.beyondata.de.s3.amazonaws.com/local/automatic/Newssite/Airline+Reporter/100th+Birthday+Boeing+Surprise+A+Special+Alaska+Livery_3xZTIo.html

Is that the expected behaviour, a bug or do I need different options?

Thanks a lot!
Marcel

**Comment by remy** [comment]
I ran the page in Chrome and watched the network tab. What I can see is that there's an ad that's been inlined, but that then constructs new requests—so inliner can't capture these.

I can't see fonts being requested, nor CSS - can you point these out so I can take a closer look?

One thing I did notice however, is that the page uses `img` elements with `srcset` which isn't supported (rather an oversight) and in Firefox, it won't defer to the original source if the network is down. I'll raise a feature request for `srcset` too.

**Comment by ibrahimabdo** [comment]
I have the same issue. I have two scripts included in my html file (jquery and bootstrap) and after running the command `inliner index.html > index.min.html` instead of being embeded inside the html file, they are still linked.

The other resources, like css and images are correctly embedded, but not the js files.

**Comment by remy** [comment]
@ibrahimabdo can you provide a real HTML (in a gist or something) so I can create a test for it?

**Comment by ibrahimabdo** [comment]
@remy yes, here is a link to both original and compressed version:

original: http://cloudr.tk/inliner/test.html
inliner: http://cloudr.tk/inliner/test.min.html

**Comment by ibrahimabdo** [comment]
So, after a little debugging inside the code, i've discovered that in my case I should have used `-m` parameter to include the minified scripts. Not that obvious though.

**Comment by remy** [comment]
No, I agree. I want to make that a default (it was only added recently and minified scripts was entirely ignored). I've not gotten to the bottom of where that hex symbol is coming from yet though…

**Comment by ibrahimabdo** [comment]
Found it.
Looks like it's from **cheerio** module. Don't know why, but moving the line `cheerioLoadOptions.decodeEntities = false;` outside of `if (enc !== 'utf-8') {` fixed the issue with the hex symbol.

**Comment by marcelboettcher** [comment]
@remy Thanks a lot for investigating! I check and you are right, those are all requests made by javascript, which you cannot capture.

So the issue is solved for me. Thx!
