### ISSUE TITLE
Add option to not remove HTML comments

### ISSUE THREAD

**Issue by camiblanch** [remy/inliner#110]
This would be nice because the HTML I am looking to use this for uses comments for includes like this `<!--#include virtual="/includes/head.html"-->`

**Comment by remy** [comment]
Isn't it the case that any server side parsing of the comments tends to starts with `<!--#` - I could just check the body of the comment, and if it starts like that, don't strip it.

What do you think?

**Comment by camiblanch** [comment]
Thanks! That seemed to do the trick
