### ISSUE TITLE
SVG Unbound namespace prefix: "xlink"

### ISSUE THREAD

**Issue by HugoGresse** [remy/inliner#111]
When svg in html pages use `xlink` the inliner stopped with the following error:

```
Unbound namespace prefix: "xlink"
```

To reproduce, having this in the html: 
```
<image width="50" height="50" xlink:href="http://referentiel.nouvelobs.com/logos/svg/logo-challa-appli.svg" src="http://referentiel.nouvelobs.com/logos/png/logo-challa-appli.png" alt="Challenges"></image>
```

**Comment by remy** [comment]
Can you give me a fuller example, i.e. the full html file? I can't replicate with this alone (probably mostly due to lack of understanding of the problem).

**Comment by HugoGresse** [comment]
Ok, you can check with 
```
inliner www.sofoot.com
```

**Comment by remy** [comment]
When I scan the source of www.sofoot.com (after being inlined), I can't find `<image` anywhere. Can you give me any more information on where to find this issue?

**Comment by HugoGresse** [comment]
I've updated inliner to 1.6.4 and xlink seems to work. (I was on 1.6.2). 

thanks!
