### ISSUE TITLE
Will this run from the PHP exec function?

### ISSUE THREAD

**Issue by schester44** [remy/inliner#112]
I'm trying to run this from PHP and I can't seem to get any output. It will create the output file but the output file is empty. I run the same command in the CLI and it works perfectly. Am I missing something? How can I get this to run ?

**Comment by schester44** [comment]
was able to get around this by using curl.

```
$string = 'curl http://localhost/input_file.php | inliner > output_file.html';
exec($string);
```

**Comment by remy** [comment]
Bit weird, but glad you worked it out.
