### ISSUE TITLE
Don't recommend appcache

### ISSUE THREAD

**Issue by arkon** [remy/inliner#114]
[Appcache](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) is deprecated, while [service workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) are the preferred method of making things available offline now.

**Comment by remy** [comment]
It's depreciated? Where? https://www.w3.org/TR/2011/WD-html5-20110525/offline.html

But also, I don't remember *recommending* appcache, only suggesting that an inlined page can be used with one. Happy to take a PR to remove any such recommendation. Will close in lieu of PR. Cheers.

**Comment by arkon** [comment]
The [updated spec](https://html.spec.whatwg.org/multipage/browsers.html#offline) notes that it's in the process of being removed.
