### ISSUE TITLE
Exclude specific images from inlining

### ISSUE THREAD

**Issue by jeannekamikaze** [remy/inliner#118]
Would be interesting if the script could exclude specific images from inlining. Use case: website uses a texture atlas to hold images that appear in all its pages. Inlining the atlas creates huge page files, but on the other hand, inlining the other images still provides a performance improvement. It would nice to be able to inline all images but the atlas.

**Comment by remy** [comment]
You'll need to require the inliner module in and block out those resources as it's going through the URLs. I'm not 100% on the code required, but I'm pretty sure someone else had a similar requirement.
