### ISSUE TITLE
Inlining should skip script templates

### ISSUE THREAD

**Issue by hkdobrev** [remy/inliner#120]
I use this awesome inliner for packaging a [reveal.js](https://github.com/hakimel/reveal.js/) presentation in a single file. Reveal.js supports using Markdown for writing slides content. It does that by using `<script type="text/template"></script>` tags which is used in other cases as well like Angular.js templates. I think the inliner should skip these scripts even when inlining CSS and JS.

Here's a simple [example reveal.js presentation with Markdown using the inliner](https://github.com/hkdobrev/service-providers-slides/blob/4b8db461c07d2e9951a25aa987c2ceac280e417d/source.html).

**Comment by mwcz** [comment]
If this is implemented, I'd like to request a CLI flag to toggle it on/off.  I use nonstandard script tags for GLSL shaders (`<script type="x-shader/x-vertex">`) and very much want them to be inlined.  Any default behavior is fine with me, as long as a flag allows for inlining everything, or inlining certain types.

**Comment by remy** [comment]
In progress…some 6 months later!

There was code to handle this, but what's actually happening is the white space is being collapsed. A temp work around is to use `--nocompress`, but I'm in the process of fixing this at the source so it doesn't collapse white space in scripts (after compression). For example, currently inliner would collapse the whitespace in a multiline ES6 template.

**Comment by hkdobrev** [comment]
🎉
