### ISSUE TITLE
Feature request: Support for html imports

### ISSUE THREAD

**Issue by niklas-dahl** [remy/inliner#128]
Html imports enable you to import html with html:

`<link rel="import" href="/path/to/imports/stuff.html">`

The Polymer project uses them a lot for their webcomponents so it would be awesome if this `inliner` could understand them and inline them aswell.

Thanks.

**Comment by remy** [comment]
I appreciate this was months ago, but do you want to take a shot at a PR? The tests are very easy to setup (follow the contributing doc - just need two HTML files). Thanks so much!
