### ISSUE TITLE
API to just give a list of resources

### ISSUE THREAD

**Issue by trajano** [remy/inliner#132]
Part of the README says that it will gather a list of all the resources being used by a page.  I was wondering if there is an API that you can provide that just gives me the straight list.

**Comment by remy** [comment]
Um, I think I follow what you want, but no, it won't operate like that. You can require inliner and listen to progress events, but it won't just list the resources. You probably want `wget` with the `--spider` option (and perhaps like a dry-run flag or something, so it just spiders but doesn't download?).
