### ISSUE TITLE
How to use INLINER with CURL cookied file?

### ISSUE THREAD

**Issue by drquochoai** [remy/inliner#133]
I'm using CURL to login to a page and i want to download logged in pages.
INLINER cannot loggin to a page, so he cannot download that pages.
How can combine 2 of them to download and inliner downloaded page?
Thanks for your help!

**Comment by remy** [comment]
You can add headers so you can manually add the validated headers to the request.

Something like `inliner -H 'cookie: xxx=yyy'` I believe.
