### ISSUE TITLE
Inlining fonts doesn't seem to work correctly.

### ISSUE THREAD

**Issue by jordwalke** [remy/inliner#142]
I had to place the `@import url("../fontSupport/montserratCSS.css");`at the *bottom* of my CSS file instead of the top, for this to work. Note, I'm loading an html file off of the local file system (not sure it matters).

This [other project](https://github.com/zTrix/webpage2html) works correctly even with the import at the top of the css file - worth looking into what they do differently.

As a result of what ever `inliner` is doing, all the following CSS rules are not processed.

**Comment by jordwalke** [comment]
<img width="968" alt="screen shot 2017-04-14 at 5 17 39 pm" src="https://cloud.githubusercontent.com/assets/977348/25059162/4e84c5a4-2136-11e7-91d4-c8feeb181bb5.png">


on the left side is what `inliner` does, and the right is what `webpage2html` does.

**Comment by jordwalke** [comment]
I'm pretty sure it's just that dangling (incorrect) semicolon.

**Comment by remy** [comment]
Can you upload a small gist that contains the files to replicate this? I can then make a test case against it to fix the issue.

**Comment by remy** [comment]
Any chance of the test case?

**Comment by jordwalke** [comment]
```
The gist is just that you put this in any css:
```
@import url("../fontSupport/montserratCSS.css");
```
And the result is like the screenshot on the left - a dangling semicolon appears.

I believe that the `@import` should have a semicolon in the input, but not font-face (in the output)

**Comment by specious** [comment]
I'm getting the trailing semicolon after the CSS import.

**index.html**
```html
<html>
<head>
  <link rel="stylesheet" href="main.css">
</head>
</html>
```

**main.css**
```css
@import url("second.css");
```
**second.css**
```
body {
  background-color: black;
}
```

The output is:

```html
<html> <head> <style>body{ background-color:black;};</style> </head> </html>
```

**Comment by specious** [comment]
Current test results for CSS imports, for example [test/fixtures/css-ext-import.result.html](https://github.com/remy/inliner/blob/552851733ce175ab7f4e6397855159a08900d8a5/test/fixtures/css-ext-import.result.html#L1), show the same `;` after inlining a CSS `@import`.

**Comment by specious** [comment]
I think what's happening is the [trailing semicolon terminating the @import statement](https://github.com/remy/inliner/blob/552851733ce175ab7f4e6397855159a08900d8a5/lib/css.js#L63) isn't being erased when said statement is [replaced with the imported contents](https://github.com/remy/inliner/blob/552851733ce175ab7f4e6397855159a08900d8a5/lib/css.js#L81).
