### ISSUE TITLE
Support basic XMLHTTPRequest

### ISSUE THREAD

**Issue by jordwalke** [remy/inliner#143]
It would be great to have basic XMLHttpRequest support. Meaning, any network requests that you make during startup can be captured (I would say it could only record the first round of async requests while loading the page and then that would be sufficient for many important use cases). I have some specific ones in mind.

**Comment by remy** [comment]
I'm afraid​ that's way way out of scope for this project. If content is required from XHR requests, I'd argue it should be there in the markup already.

**Comment by jordwalke** [comment]
It's impossible to load local files from other local files when loading a local html page. So for those use cases, xhr is the only solution and can't be loaded via traditional script tags etc.
