### ISSUE TITLE
Is there a way of using inliner in an asynchronous way?

### ISSUE THREAD

**Issue by lucasmf** [remy/inliner#144]
I tried something like:
```
var inliner = new Inliner('http://remysharp.com')
// trying to use the returned promise
yield inliner.promise
```
but it didn't work out, should I be able to use this promise at all?
Thank you.

**Comment by remy** [comment]
It is async and I'm pretty sure I don't document anywhere that it returns a promise. It uses the callback pattern or you can hook event handlers.
