### ISSUE TITLE
Test comparing undefined with undefined.

### ISSUE THREAD

**Issue by lucasmf** [remy/inliner#145]
Hello,

I believe there's something wrong with the following test:
```
 t.equal(Inliner.version,
   require('../package.json').version, 'should have version');
```
package.json doesn't have a field named ```version``` , and I believe Inliner doesn't have also. So it ends up comparing undefined with undefined.

Thank you!

**Comment by remy** [comment]
Yup, good catch. That shouldn't be in there. I'll push up a fix.
