### ISSUE TITLE
Creates empty html

### ISSUE THREAD

**Issue by MichaelRFox** [remy/inliner#146]
I'm attempting to use inliner via the cli to bundle a single html which has tags for one css and one js file.  All are located in the same local directory.  When I execute the commend "inliner -n index.html > bundle.html", a blank bundle.html file is created and nothing else happens.  I have to press ^c to exit the cli.

I'm sure I'm doing something really silly.  My html below:

<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta charset="utf-8">
		<title>Taxonomy</title>
		<link rel="stylesheet" href="https://index.css">
		<style>
			@import url('index.css');
		</style>
	</head>
	<body>
		<script type='text/javascript' src='https://fxTree.js'></script>
		<script>
			fxTree();
		</script>
	</body>
</html>

**Comment by remy** [comment]
Is that the source html?

**Comment by MichaelRFox** [comment]
Yes.  I tried several variations of the link urls including relative,
absolute, and sticking an "https://" on the front...no luck.

BTW, I'm using Git Bash on Windows 10...node and npm are latest versions.

**Comment by MichaelRFox** [comment]
I was finally able to achieve success by using the following command in my package.json script:
` `` javascript
 "inline": "cd dist & cat index.min.html | inliner -nim > build.min.html & cd .."
```
I had to use the cd command because inliner could not locate the link js and css files otherwise

**Comment by remy** [comment]
👍
