### ISSUE TITLE
Inline special external (Markdown, CoffeeScript) files

### ISSUE THREAD

**Issue by Leftium** [remy/inliner#157]
External files can be referenced from "special" HTML tags. For example:
- [Markdown files in a Reveal.js presentation](https://github.com/hakimel/reveal.js#markdown)
- [CoffeeScript files](http://coffeescript.org/#scripts)

It would be nice if inliner supported these external files. There are likely other types of external files, so I suggest a generalized method of specifying tags with external files that should be inlined, or a plug-in system.

I would like to inline external Markdown files from my Reveal.js presentations, thus separating my content from the HTML boilerplate. However, I have not found an inliner that does this, yet. This [comment](https://github.com/hakimel/reveal.js/issues/788#issuecomment-298866406) indicates other people are interested in inlining external Markdown, too.

---

Here is sample syntax for an external Markdown file in Reveal.js:
``` html
<section data-markdown="example.md"  
         data-separator="^\n\n\n"  
         data-separator-vertical="^\n\n"  
         data-separator-notes="^Note:"  
         data-charset="iso-8859-15">
</section>
```
Notes:
- the inlined content must be wrapped in a `<textarea>` or `<script>` tag
- other HTML attributes should be preserved

The inlined output should look like this:
``` html
<section data-separator="^\n\n\n"  
         data-separator-vertical="^\n\n"  
         data-separator-notes="^Note:"  
         data-charset="iso-8859-15">
	<textarea data-template>
		CONTENTS OF: example.md
	</textarea>
</section>
```

---

And sample syntax for an external CoffeeScript file:
``` html
<script src="sample.coffee" type="text/coffeescript"></script>
```

This tag can be treated like a normal external JavaScript file. No extra processing is required.

**Comment by remy** [comment]
This is a nice idea, but I'm afraid it's out of scope for this kind of project. The principle of this project is that it will render exactly the same as the original page - and this feature suggestion suggests that there would be some (magic) transform that happens in between.

I think a PR that adds some kind of hook to allow for transforms would be better suited, but again, I'm not 100% sure it would be that useful to the broader audience.

Thank you all the same.
