### ISSUE TITLE
Maximum call stack size exceeded when using Google Closure library

### ISSUE THREAD

**Issue by juliendurand** [remy/inliner#16]
Hi,

Your inliner is just what I was looking for and is absolutely great.

I am however getting the error message "Maximum call stack size exceeded" when using "inliner -vni" on a project built with the Google Closure library. 

This is originating from jsUglify.

What would you think about being able to use different kind of minifier/compiler/uglifier/... to process the scripts ? Ideally I would use Google closure for this project (which is also likely to resolve the issue above).

I have looked at your code and I believe this should be a resonably easy thing to do. I guess the difficult part is to launch a java VM, launch the Closure compiler class and get the result back into node. I have never done that and do not know if it's even possible. Would you be interested by this work? or should I fork you code ?

**Comment by remy** [comment]
Happy to reopen, but this might be fixed in the newly released 1.0.0 or you might not care anymore (it's been 3 years!) otherwise, if you can provide a sample command  I can take a look.
