### ISSUE TITLE
Expand on installation/use instructions

### ISSUE THREAD

**Issue by mpiasta-ca** [remy/inliner#17]
No idea how to use inliner. Can you give more instructions? Can't find any details online.

I got so far as to install node.js server. When I run "inliner http://remysharp.com" in cmd I get one of two responses: 

1-
Fatal error parsing HTML - exiting :: http://remysharp.com

or...

2 -
path.existsSync is now called 'fs.existsSync'.

When I try it with the other method - 

var Inliner = require('inliner');
new Inliner('http://remysharp.com', function (html) {
  // compressed and inlined HTML page
  console.log(html);
});

I look in console, and I get the error:

'Uncaught ReferenceError: require is not defined'

Can you expand on what I'm supposed to do after "npm install inliner" finishes...?

**Comment by chevdor** [comment]
Same issue here. The documented sample fails.

**Comment by remy** [comment]
This is fixed @ 1.0.0.
