### ISSUE TITLE
Javascript inlining / importing clarification

### ISSUE THREAD

**Issue by Terrabits** [remy/inliner#176]
Per `README.md`:

> If JavaScript can't be imported (or is Google Analytics), source is not put inline

Can you clarify what this means? Does it fail if the .js source is not accessible? Or is this a reference to ES2015's "import" statement?

On a related note, will it `curl` remote (CDN) assets and inline those as well?

Thanks!

**Comment by remy** [comment]
No, this isn't es6 imports. Though, es6 imports aren't inlined at all. This line refers to any failures to request the script, and if it fails, it leaves the script src as is.
