### ISSUE TITLE
Errors while trying to get resources/install

### ISSUE THREAD

**Issue by lloydi** [remy/inliner#18]
As requested, here's what I was getting while trying to install inline (copied/pasted the parts you suggested I need). Hope you're able to fix it:

xtify@0.1.3 install /usr/local/lib/node_modules/inliner/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/lloydi/.node-gyp/0.8.14"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/inliner/node_modules/jsdom/node_modules/contextify/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.8.14/node-v0.8.14.tar.gz
gyp http 200 http://nodejs.org/dist/v0.8.14/node-v0.8.14.tar.gz
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:297:15)
gyp ERR! System Darwin 12.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/inliner/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.8.14
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing contextify@0.1.3
/usr/local/bin/inliner -> /usr/local/lib/node_modules/inliner/bin/inliner
inliner@0.1.14 /usr/local/lib/node_modules/inliner
├── commander@0.5.1
├── uglify-js@1.2.2
└── jsdom@0.2.19 (cssom@0.2.5, request@2.11.4, cssstyle@0.2.3, htmlparser@1.7.6)

**Comment by remy** [comment]
This is fixed @ 1.0.0.
