### ISSUE TITLE
CLI fails when called from a bash script in Eclipse

### ISSUE THREAD

**Issue by sdc-andy** [remy/inliner#189]
I am trying to integrate the inliner command line tool into a bash script that is then called by Eclipse prior to compiling a project in which the web content is embedded.

When the bash scripts executes, the output window in Eclipse just shows:

`[?25l

[1A[s`

The .html output file is also 0 bytes.

I suspect this is down to the use of ANSI within the output process.  Is there a way to disable this?

-Andy.

**Comment by hoffa** [comment]
Hey, check this out: https://github.com/remy/inliner/issues/151#issuecomment-428368034
Worked for me. Seems it's assuming a TTY.

**Comment by sdc-andy** [comment]
Thanks, that seems to have fixed it.

-Andy.
