### ISSUE TITLE
inliner.js: urlMatch regexp currently fails on valid CSS image url declarations, proposed fix

### ISSUE THREAD

**Issue by spacez320** [remy/inliner#20]
Currently if you use spaces before or after the url value in in url declaration in CSS, such as `url( "something" );` the function `getImagesFromCSS` trips up.

Proposed solution (get ready for this) is adjust the `urlMatch` regexp (inline.js:463) to:
```javascript
urlMatch = /url\((?:[ '"]*)(?!['"]*data:)(.*?)(?:[ '"]*)\)/g
```

**Comment by remy** [comment]
This is (indeed) fixed in 1.0.x (tests included).
