### ISSUE TITLE
Use of a 'simpler' DOCTYPE

### ISSUE THREAD

**Issue by jmeas** [remy/inliner#33]
One of the features of inliner is that it uses a 'simpler' DOCTYPE. It is true that it uses a shorter one, but changing the DOCTYPE has no benefits that I know of, and has negative consequences for email development.

The DOCTYPE it forces you to use isn't just a simpler one, as it's also, of course, the DOCTYPE for HTML5 documents. This is the latest DOCTYPE, but in this case there is hardly any gain in using it. In fact, both [emailonacid](http://www.emailonacid.com/blog/details/C13/doctype_-_the_black_sheep_of_html_email_design) and [campaign monitor](http://www.campaignmonitor.com/blog/post/3317/correct-doctype-to-use-in-html-email/) suggest using the xhtml1 DOCTYPE when it comes to email. But they also leave it open to the developer to choose what they'd like to use, as your choice affects how the email renders in numerous clients.

On the side of web development, why force someone over to a new DOCTYPE if they're not building an HTML5 site? Sure, there's no harm done, but there's also no benefit.

The point I'm trying to make is that switching to a 'simpler' DOCTYPE probably isn't a good idea for this project, given that email developers might be developing around other DOCTYPES, and I can't think of any benefits of this feature.

Suggestion: Make the feature optional, at least. Personally, I wouldn't even have it turned on by default. Just leave the DOCTYPE the way it is.

**Comment by remy** [comment]
This is fixed @ 1.0.0.

**Comment by jmeas** [comment]
:trumpet:
