### ISSUE TITLE
Warn about unsupported protocols

### ISSUE THREAD

**Issue by rauschma** [remy/inliner#35]
I’m currently getting the following error. More information would be useful in such cases: what is the unsupported prototcol? What is the problematic URL?

    /usr/local/lib/node_modules/inliner/inliner.js:553
      return http[oURL.protocol.slice(0, -1) || 'http'].request(options);
                                                        ^
    TypeError: Cannot call method 'request' of undefined

The URL that didn’t work is: http://ecma-international.org/ecma-262/5.1/

**Comment by remy** [comment]
This is fixed @ 1.0.0.
