### ISSUE TITLE
Travis won't accept pull requests

### ISSUE THREAD

**Issue by mccartney** [remy/inliner#42]
Travis Continuous Integration won't accept full requests for this project, because of some infrastructure problem. The actual message reported is:
```
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```
e.g. [https://travis-ci.org/remy/inliner/builds/21471899]

**Comment by remy** [comment]
This is supported @ 1.0.0.
