### ISSUE TITLE
can we run on a file instead of url in the command line

### ISSUE THREAD

**Issue by pashupathi** [remy/inliner#49]
Can we run inliner on a file instead of url in the command line? Please help

**Comment by wappo-co** [comment]
+1

**Comment by remy** [comment]
What happened when you tried?

(Aside from inline being utterly out of date and maybe not working/in the
process of a rewrite...but might work, I know this is supported out of the
box, which begs the original question).

**Comment by remy** [comment]
This is supported @ 1.0.0.
