### ISSUE TITLE
404 results in a fatal error

### ISSUE THREAD

**Issue by dtjm** [remy/inliner#61]
Hi, first of all thank you for writing this tool. I've been wanting to make something like this for a while.

I am trying to pull down [this web page](http://danquyen.com/?cmd=act:news%7Cnewsid:17931) but one of the links resolves to a 404 error, which halts processing of the page.  Would you be open to introducing a flag that ignores the 404 error and leaves the link as-is?  

I would be glad to try to make a pull request, but would need some hints as to where to start.

Thanks!

**Comment by remy** [comment]
It makes sense to *not* bail on 404/by default actually. The code change is
in find-asset.js where it throws if the status is not 200.

**Comment by remy** [comment]
Sorry, just to add if you want a crack, please do. It should be straight
forward, but one of the current PRs tries to address it but uses fallback
content which I'm not quite on board with (and also checkout the
contributing doc as it'll explain how to add tests - which is easy!).

**Comment by dtjm** [comment]
I'm not seeing a check for 200 in https://github.com/remy/inliner/blob/master/lib/find-assets.js, although I do see it here:  https://github.com/remy/inliner/blob/master/lib/get.js#L58

However, I'm trying to figure what do to there. I'm thinking of something like this:

```js
      if (error || (res && res.statusCode != 200)) {
        resolve({ url: url });
      } else {
        resolve({ headers: res.headers, body: body });
      }
```

but I can't figure out what code is consuming that promise.

**Comment by remy** [comment]
Oh, you're right - that's attached to `inliner.get` and reused across all the asset collection.

So, I think that `body` should probably be a blank string...and then resolve. I think it's also worth triggering a warning on the `progress` event, via:

```js
inliner.emit('progress', res.statusCode + ' on ' + url);
```
