### ISSUE TITLE
Inlining a string

### ISSUE THREAD

**Issue by johngeorgewright** [remy/inliner#66]
Hey there,

Is there a way to use inliner without requesting a URL, but instead just passing giving it a string of HTML?

Ta.

**Comment by remy** [comment]
Hmm. I don't think there is. It could do with a feature that reads from stdin so you can `echo "<html>...." | inliner`.

You can point inliner to a file though (as a workaround for now).

**Comment by FelixAkk** [comment]
I'd love to see this ability too :) so I made a start at supporting it in the above mentioned pull request.

**Comment by remy** [comment]
Live in latest release
