### ISSUE TITLE
Resolving URLs in local files breaks them

### ISSUE THREAD

**Issue by FelixAkk** [remy/inliner#70]
I noticed that Inliner resolves URL's in files such as `http://someplace.com/icon.png` to something like `/location/file/http:/someplace.com/icon.png`, which obviously breaks the link. I can't imagine this is wanted behavior, so I propose the below mentioned pull request as a fix.

Great work on this handy utility by the way!

**Comment by FelixAkk** [comment]
I see it breaks a test fixture. I'm not familiar with Travis so forgive my lack of knowledge. The file it crashes on looks very similar to what I'm trying to Inline, and the fault it crashes on is exactly the one I attempt to fix with that pull request (and which does so when testing here) ... I'm a little confused :)

**Comment by remy** [comment]
Commented on the PR.
