### ISSUE TITLE
svg...

### ISSUE THREAD

**Issue by dotob** [remy/inliner#77]
hi remy,

any plans when the work you did in the feature svg branch will be available in master? anything that can be done to help?

dotob

**Comment by remy** [comment]
I thought it was in: https://github.com/remy/inliner/commit/9904b6b3346f216b22792b19579eb160077cb1db

Also - it's there in the help...are you seeing it too?

<img width="695" alt="screen shot 2015-11-26 at 19 37 35" src="https://cloud.githubusercontent.com/assets/13700/11429810/2dfad2dc-9475-11e5-9ae1-35a0fc69de7b.png">

**Comment by petr-inmite** [comment]
I can confirm the SVG feature is in latest NPM available on Mac at the time (1.6.1).
