### ISSUE TITLE
Filesystem load has issues with URL markup.

### ISSUE THREAD

**Issue by verm** [remy/inliner#84]
Great software -- works very well!

When loading a file from the filesystem some URLs won't load for example:

  `ENOENT, open '//build/singlehtml/_static/fonts/fontawesome-webfont.eot?v=4.2.0'`

I'm merging htmlsingle ouput from Sphinx into one file.  If I parse the file and remove the `?v=4.2.0` it works perfectly.

Thank you!

**Comment by remy** [comment]
What version of inliner are you using? IIRC querystrings web supposed to be stripped (in another bug fix some months ago).

**Comment by verm** [comment]
1.8.0 is what Node installed.  I didn't think to try the Git version, sigh.  I will give it a shot later and report back.
