### ISSUE TITLE
Feature Request:  Allow login prior to 'inlining' page

### ISSUE THREAD

**Issue by rhefner** [remy/inliner#85]
Awesome module!  I've been wanting to use this to inline some page(s) which are behind a login form, which I can't bypass (simple user/pass + submit).  It would be great if this could support logging in, then taking a snapshot of the page that I really want vs. the login form itself.

I may be missing something, but I wasn't sure if I could chain actions, like with PhantomJS modules (horseman, etc.)?

**Comment by remy** [comment]
Being able to script (to login, etc) inliner could easily get out of control (re: features), but you can set a cookie header using the `--header LINE` to request the page with a valid logged in cookie.
