### ISSUE TITLE
-I flag to add additional include dir to inliners search path

### ISSUE THREAD

**Issue by xy124** [remy/inliner#89]
It would be useful to have an option like this, especially when using inliner within another js-library to get rid of those:
```
[Error: Invalid URI "js/reveal.js"]
```

**Comment by remy** [comment]
Can you give me an example of how this happening for you?

**Comment by xy124** [comment]
_Short version_: relative asset paths in html file are not the same as on servers file system.

_long version_:
Imagine there is a node webserver serving pages. 
I want to inline those served pages on server side before sending them. 
The pages rely on assets, e.g. css/style.css .
So for the un-inlined version the browser is sending a request for GETing css/style.css  after getting index.html .
The node server would normally link the css-directory request user specific with e.g. filesystem node user1234/css/style.css ...

But now I want to inline all those styles etc. into index.html . So I would love to configure possible asset search paths as one can do it e.g. for gcc's incude paths ;)

I'm already trying to implement this. Besides being caught by promise hell a bit, It seems as I only need to add one more (commandline-)option and do some file existence checks in get.js .

I naturally would appreciate your help or if you could even name some promising promise resources ;)

**Comment by remy** [comment]
http://www.html5rocks.com/en/tutorials/es6/promises/

This does seem very bespoke, or at least only makes sense if you're making it middleware, so at the least, I would not add another CLI option. 

I'll be honest, I'd rather see some other interest in this feature before landing it in master.

**Comment by remy** [comment]
Thinking some more about it, some that might work without any need for a change is if you changed the behaviour of `lib/get.js` via Inliner's prototype. That way you can handled all the responses yourself and decide whether to retrieve them from a different location, then when you return, the rest of the inliner would handle inlining etc.

**Comment by xy124** [comment]
Great idea! I hope I understood you right. You propose overriding Inliner.prototype.get ?

**Comment by remy** [comment]
Yep.

**Comment by remy** [comment]
Wondering how you got on with this? I think it would make a good addition to the documentation if you were able to intercept the requests.

**Comment by xy124** [comment]
atm I'm stuck at a bug of css imports that are not resolved correctly. Next weeks are full of no _computer travels_ and exams. I guess when university starts again in April I will have time to investigate in this again ;)

**Comment by remy** [comment]
No problem. If I can find some downtime, I might be able to mock up a contrived example of this too.

Good luck with the exams!

**Comment by xy124** [comment]
finally after successfully passing my exams :smiley:  and taking some holiday :palm_tree: , I found some time to investigate in this. 
As I said on 2nd of March  there seems to be a bug in import handling (at least chromium & co search at a different location). 

To reproduce 

in a html file to inline is a line like:

```
<link rel="stylesheet" href="folder1/style.css">
```

in folder1/style.css the following line is written:
```
@import url(../folder2/style2.css)
```

in folder2/style2.css:
```
@font-face {
	src: url('also-in-folder2.woff');
}
```
`also-in-folder2.woff` is searched for in `folder1` !
but that is wrong! (path relative to `style2.css`)

I guess an easy reproducible testing field is trying to inline the `index.html` of a reveal.js - presentation !

@remy maybe you could investigate in this?!?

**Comment by remy** [comment]
Wanted to check - how are you inlining? Specifically the terminal command you're running?

I'm able to replicate when I pipe the content into inliner using `cat somefile.html | inliner` and I know why this breaks, but I wonder if you're doing something similar?

**Comment by xy124** [comment]
yep I run inliner as a lib: 
```js
var inliner = require('inliner');
new inliner (html, function(error, inlinedHTML) {
...
});
```

> and I know why this breaks

can you fix it or tell me why, please?

**Comment by remy** [comment]
Makes sense. So the problem is that when the HTML is sourced straight into inliner, it thinks it's reading from a remote source (i.e. it should be in "file" mode instead). 

I'm happy to fix up, I'm sure the fix will work for both usages.

**Comment by xy124** [comment]
:+1: nice man!

**Comment by remy** [comment]
Release is deploying now - should land in 1.9.1.
