### ISSUE TITLE
Published NPM has CRLF bug

### ISSUE THREAD

**Issue by bluecmd** [remy/inliner#90]
Hi,

Seems like inliner is affected by https://github.com/npm/npm/issues/2097

I ran:
`npm install -g web-combiner`

File inliner.js gives:
`/usr/lib/node_modules/web-combiner/inliner.js: Node.js script, ASCII text executable, with CRLF line terminators`

This is a problem in UNIX systems as it will try to execute '/usr/bin/node\r':
```
$ inliner
: No such file or directory
$ strace inliner
...
execve(/usr/bin/node\r", ["node\r", "/h"...], [/* 120 vars */]) = -1 ENOENT (No such file or directory)
...
```

**Comment by remy** [comment]
Okay, so firstly you're installing `web-combiner` and reporting against inliner - which is cool, since I didn't know about the other tool (it looks like they used my code from a few years back as a base).

I'd recommend `npm install -g inliner` and you'll be all good :smile:
