### ISSUE TITLE
[npm - WARN peerDependencies] The peer dependency tap@* included from tap-only will...

### ISSUE THREAD

**Issue by float-mode** [remy/inliner#92]
During the installation, I got these warnings about the TAP@ dependency not being future proof... 

![screen](http://cooldept.com/f/floatmode-bash-bash-101-34-1_160401-ksavf.png)

I have a very little clue of node or npm and its dependencies. Far from an expert here, It's more of an experiment for me than anything... So I'm not sure if this is an issue exactly, but I thought I create a record of it, in case you need to track it. And if you have any advice for me and if I need to do anything that can fix this. (installing npm 3 ?)

**Comment by remy** [comment]
That's a bug, I've just pushed a new version and it should deploy in the next few minutes.

`tap-only` should have been a dev dep, and not a production dep - which explains why you're seeing the exception.

Thanks for raising the issue and getting my eyes on this!
