### ISSUE TITLE
use a ServiceWorker + tar.

### ISSUE THREAD

**Issue by graingert** [remy/inliner#93]
Instead of Base64 encoding URLs you could use the real URL and store the data in a .tar file. Then use a service worker to fulfil the URLs from the tar file.

**Comment by remy** [comment]
I like the idea of this, but it would have to be opt in. Why the tarball though? Or would that be intended to be untarred in the user's directory?

**Comment by graingert** [comment]
@remy the files created would be an index.html, and a serviceWorker.js with a tar BaseXML encoded and appended to a <script type='not application/javascript'></script> tag.

* The index.html boots the ServiceWorker and sends it the content of the script tag
* the serviceworker BaseXML decodes the content passed to it
* the ServiceWorker then responds to requests from the html page by untaring the files out of the decoded content.

**Comment by graingert** [comment]
https://github.com/kriswebdev/BaseXML

**Comment by graingert** [comment]
this allows you to take any number of pages, images and videos and convert them into a two pages

**Comment by remy** [comment]
I'd be happy to see you take a stab at this. I'd recommend trying to approach it, WRT inliner, as a plugin of sorts that can be enabled via flag.

**Comment by remy** [comment]
I'm going to close this (given it's almost a year now), but also, I'm not entirely sure it's a common use case. 

I'd love to see inliner required into a module that does this, but I don't think it belongs in the code module.

Thanks again for raising the idea.
