### ISSUE TITLE
[TypeError: Cannot read property 'filter' of undefined]

### ISSUE THREAD

**Issue by hus787** [remy/inliner#95]
Inlining http://www.fool.com/investing/general/2016/04/09/is-snapchat-a-threat-to-facebook-2-charts-offer-co.aspx

returns [TypeError: Cannot read property 'filter' of undefined] in the call back

Version: 1.8.2

**Comment by remy** [comment]
Can you rerun the same command but include `-d` as an additional argument and paste in the full output from the terminal? This will help me debug.

Cheers.
